// Semver ranges for @emberkit/* packages written into generated projects.
// Regenerated by scripts/sync-cli-template-versions.mjs from packages/*/package.json.
// That script also sets packages/ui workspace:^ deps for @emberkit/core and @emberkit/icons.
export const EMBERKIT_PACKAGE_VERSIONS = {
  core: "^0.2.8",
  ui: "^0.3.4",
  icons: "^0.2.6",
  cli: "^0.6.4",
  edge: "^0.2.3",
  tsconfig: "^0.2.1",
} as const;
