import type { FC } from '@emberkit/core';
import {
  IconMenu, IconX, IconSearch, IconSun, IconMoon, IconGithub,
  IconChevronDown, IconChevronRight, IconChevronLeft,
  IconArrowRight, IconArrowUp, IconArrowDown,
  IconPlay, IconPause, IconCode, IconBook, IconZap, IconPackage,
  IconTarget, IconType, IconCopy, IconCheck, IconAlertCircle,
  IconExternalLink, IconPlus, IconMinus, IconTerminal, IconLayers,
  IconGrid, IconSettings, IconGlobe, IconImage, IconFile, IconFolder,
  IconEdit, IconTrash, IconHeart, IconStar, IconHome, IconUser,
  IconUsers, IconLock, IconMail, IconCalendar, IconClock, IconMapPin,
  IconLink, IconRefresh, IconShield, IconCloud, IconDownload, IconUpload,
  IconAlertTriangle, IconInfo, IconFilter, IconShare, IconBookmark,
  IconTag, IconBell, IconMessageCircle, IconPhone, IconVideo, IconMic,
  IconVolume, IconVolumeX, IconPower, IconLogOut, IconLogIn, IconLoader,
  IconDatabase, IconServer, IconWifi, IconBattery, IconFlag, IconEye,
  IconEyeOff, IconThumbsUp, IconThumbsDown, IconClipboard, IconMaximize,
  IconMinimize, IconMoreHorizontal, IconMoreVertical, IconPieChart,
  IconBarChart, IconActivity, IconAward, IconCompass, IconHash,
  IconAtSign, IconSend, IconInbox, IconArchive, IconTrash2, IconScissors,
  IconCheckCircle, IconXCircle, IconHelpCircle,
  IconXTwitter, IconLinkedIn, IconFacebook, IconInstagram,
  IconYoutube, IconDiscord, IconReddit, IconTwitch, IconSlack,
  IconTikTok, IconWhatsApp, IconDribbble, IconBehance, IconPinterest,
  IconAstro, IconVue, IconAngular, IconReact, IconSvelte,
  IconNodeJs, IconNpm, IconPnpm, IconYarn,
} from '@emberkit/icons';

const registry: Record<string, FC<{ size?: number; className?: string; color?: string }>> = {
  menu: IconMenu as FC,
  x: IconX as FC,
  search: IconSearch as FC,
  sun: IconSun as FC,
  moon: IconMoon as FC,
  github: IconGithub as FC,
  'chevron-down': IconChevronDown as FC,
  'chevron-right': IconChevronRight as FC,
  'chevron-left': IconChevronLeft as FC,
  'arrow-right': IconArrowRight as FC,
  'arrow-up': IconArrowUp as FC,
  'arrow-down': IconArrowDown as FC,
  play: IconPlay as FC,
  pause: IconPause as FC,
  code: IconCode as FC,
  book: IconBook as FC,
  zap: IconZap as FC,
  package: IconPackage as FC,
  target: IconTarget as FC,
  type: IconType as FC,
  copy: IconCopy as FC,
  check: IconCheck as FC,
  'alert-circle': IconAlertCircle as FC,
  'external-link': IconExternalLink as FC,
  plus: IconPlus as FC,
  minus: IconMinus as FC,
  terminal: IconTerminal as FC,
  layers: IconLayers as FC,
  grid: IconGrid as FC,
  settings: IconSettings as FC,
  globe: IconGlobe as FC,
  image: IconImage as FC,
  file: IconFile as FC,
  folder: IconFolder as FC,
  edit: IconEdit as FC,
  trash: IconTrash as FC,
  heart: IconHeart as FC,
  star: IconStar as FC,
  home: IconHome as FC,
  user: IconUser as FC,
  users: IconUsers as FC,
  lock: IconLock as FC,
  mail: IconMail as FC,
  calendar: IconCalendar as FC,
  clock: IconClock as FC,
  'map-pin': IconMapPin as FC,
  link: IconLink as FC,
  refresh: IconRefresh as FC,
  shield: IconShield as FC,
  cloud: IconCloud as FC,
  download: IconDownload as FC,
  upload: IconUpload as FC,
  'alert-triangle': IconAlertTriangle as FC,
  info: IconInfo as FC,
  filter: IconFilter as FC,
  share: IconShare as FC,
  bookmark: IconBookmark as FC,
  tag: IconTag as FC,
  bell: IconBell as FC,
  'message-circle': IconMessageCircle as FC,
  phone: IconPhone as FC,
  video: IconVideo as FC,
  mic: IconMic as FC,
  volume: IconVolume as FC,
  'volume-x': IconVolumeX as FC,
  power: IconPower as FC,
  'log-out': IconLogOut as FC,
  'log-in': IconLogIn as FC,
  loader: IconLoader as FC,
  database: IconDatabase as FC,
  server: IconServer as FC,
  wifi: IconWifi as FC,
  battery: IconBattery as FC,
  flag: IconFlag as FC,
  eye: IconEye as FC,
  'eye-off': IconEyeOff as FC,
  'thumbs-up': IconThumbsUp as FC,
  'thumbs-down': IconThumbsDown as FC,
  clipboard: IconClipboard as FC,
  maximize: IconMaximize as FC,
  minimize: IconMinimize as FC,
  'more-horizontal': IconMoreHorizontal as FC,
  'more-vertical': IconMoreVertical as FC,
  'pie-chart': IconPieChart as FC,
  'bar-chart': IconBarChart as FC,
  activity: IconActivity as FC,
  award: IconAward as FC,
  compass: IconCompass as FC,
  hash: IconHash as FC,
  'at-sign': IconAtSign as FC,
  send: IconSend as FC,
  inbox: IconInbox as FC,
  archive: IconArchive as FC,
  'trash-2': IconTrash2 as FC,
  scissors: IconScissors as FC,
  'check-circle': IconCheckCircle as FC,
  'x-circle': IconXCircle as FC,
  'help-circle': IconHelpCircle as FC,
  twitter: IconXTwitter as FC,
  linkedin: IconLinkedIn as FC,
  facebook: IconFacebook as FC,
  instagram: IconInstagram as FC,
  youtube: IconYoutube as FC,
  discord: IconDiscord as FC,
  reddit: IconReddit as FC,
  twitch: IconTwitch as FC,
  slack: IconSlack as FC,
  tiktok: IconTikTok as FC,
  whatsapp: IconWhatsApp as FC,
  dribbble: IconDribbble as FC,
  behance: IconBehance as FC,
  pinterest: IconPinterest as FC,
  astro: IconAstro as FC,
  vue: IconVue as FC,
  angular: IconAngular as FC,
  react: IconReact as FC,
  svelte: IconSvelte as FC,
  nodejs: IconNodeJs as FC,
  npm: IconNpm as FC,
  pnpm: IconPnpm as FC,
  yarn: IconYarn as FC,
};

export type IconName = keyof typeof registry;

export interface IconProps {
  [key: string]: unknown;
  name: IconName;
  size?: number;
  className?: string;
  color?: string;
}

const Icon: FC<IconProps> = ({ name, size = 24, className, color }) => {
  const Component = registry[name];
  if (!Component) return null;
  return <Component size={size} className={className} color={color} />;
};

export { Icon };
